POST  http://localhost:16005/query
Content-Type: application/json

{
    "provider":"openai", 
    "model":"gpt-4o", 
    "history":[{
        "role":"user",
        "content":"Hello"
    },
    {   
        "role": "assistant",
        "content": "Hello, my name is Code Chat, how may I help?"
    }], 
    "message":"How are you?"
}


